### ISSUE TITLE
algorithm

### ISSUE THREAD

**Issue by coding-encoding** [jeanchristopheruel/stitcher#1]
Hello, thank you for your sharing, I am wondering about the algorithm of your code.

**Comment by jeanchristopheruel** [comment]
Hi, it's mostly based on OpenCV's [stitching module](https://docs.opencv.org/4.x/d1/d46/group__stitching.html).
I might come with my _no dependency library_ in the future but this project was more like an exploration phase.

No issue, closing the issue. You're welcome to open a [discussion](https://github.com/jeanchristopheruel/stitcher/discussions) if you want to know more about this project :)
